name: Continuous Integration

on:
  push:
    branches:
      - main  # Set the trigger to run on pushes to the main branch
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: windows-latest  # Select the latest version of Windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Clone the project

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'  # Specify the version of .NET Core SDK to install, ensure it's compatible with .NET 6.0

      - name: Restore dependencies
        run: dotnet restore  # Download dependencies

      - name: Build project
        run: dotnet build --configuration Release  # Create a project build

      - name: Run unit tests
        run: dotnet test --no-build --configuration Release  # Run unit tests
